# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_IVS.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 460)
        MainWindow.setMinimumSize(QtCore.QSize(350, 0))
        MainWindow.setStyleSheet("background-color: rgb(48, 48, 48);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(250, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_10.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_10.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 3, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_14.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_14.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 18pt \"Courier New\";\n"
"background-color: rgb(80, 21, 140);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_22.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_22.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout.addWidget(self.pushButton_22, 3, 4, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_21.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_21.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout.addWidget(self.pushButton_21, 4, 4, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_20.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_20.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 5, 4, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_13.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_13.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 3, 3, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_24.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_24.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout.addWidget(self.pushButton_24, 1, 4, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_11.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_11.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 3, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_15.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_15.setStyleSheet("color: rgb(241, 241, 241);\n"
"selection-background-color: rgb(170, 170, 255);\n"
"font: 75 16pt \"Courier New\";\n"
"background-color::hover: rgb(249,96,63);")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 2, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 80))
        self.pushButton_4.setMaximumSize(QtCore.QSize(760, 200))
        self.pushButton_4.setStyleSheet("font: 13pt \"Copperplate Gothic Light\";\n"
"background-color: rgb(221, 173, 78);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 5, 2, 1, 2)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_5.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_5.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_7.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_7.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 4, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_3.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_3.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 5, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_17.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_17.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 2, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_6.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_6.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 4, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_16.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_16.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 2, 2, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_19.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_19.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 1, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_9.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_9.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 4, 3, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_8.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_8.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 4, 2, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_23.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_23.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout.addWidget(self.pushButton_23, 2, 4, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_2.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_2.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 5, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_12.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_12.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 3, 2, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setMinimumSize(QtCore.QSize(25, 80))
        self.pushButton_18.setMaximumSize(QtCore.QSize(380, 200))
        self.pushButton_18.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 75 16pt \"Courier New\";")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setMinimumSize(QtCore.QSize(350, 60))
        self.label.setMaximumSize(QtCore.QSize(1920, 120))
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(19, 158, 119);\n"
"font: 18pt \"Consolas\";\n"
"border: 2px solid #f1f1f1;")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_10.setText(_translate("MainWindow", "4"))
        self.pushButton_14.setText(_translate("MainWindow", "1"))
        self.pushButton.setText(_translate("MainWindow", "C"))
        self.pushButton_22.setText(_translate("MainWindow", "mod"))
        self.pushButton_21.setText(_translate("MainWindow", "rand"))
        self.pushButton_20.setText(_translate("MainWindow", "!"))
        self.pushButton_13.setText(_translate("MainWindow", "*"))
        self.pushButton_24.setText(_translate("MainWindow", "("))
        self.pushButton_11.setText(_translate("MainWindow", "5"))
        self.pushButton_15.setText(_translate("MainWindow", "2"))
        self.pushButton_4.setText(_translate("MainWindow", "="))
        self.pushButton_5.setText(_translate("MainWindow", "+"))
        self.pushButton_7.setText(_translate("MainWindow", "8"))
        self.pushButton_3.setText(_translate("MainWindow", ","))
        self.pushButton_17.setText(_translate("MainWindow", "-"))
        self.pushButton_6.setText(_translate("MainWindow", "7"))
        self.pushButton_16.setText(_translate("MainWindow", "3"))
        self.pushButton_19.setText(_translate("MainWindow", "x²"))
        self.pushButton_9.setText(_translate("MainWindow", "/"))
        self.pushButton_8.setText(_translate("MainWindow", "9"))
        self.pushButton_23.setText(_translate("MainWindow", ")"))
        self.pushButton_2.setText(_translate("MainWindow", "0"))
        self.pushButton_12.setText(_translate("MainWindow", "6"))
        self.pushButton_18.setText(_translate("MainWindow", "√x"))
        self.label.setText(_translate("MainWindow", "0,000"))
